# /opt/docker-compose.yml
---
version: '3.4'
services:
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /tradebot/.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - tradingbot

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 3307:8080
    networks:
      - tradingbot

  bot:
    image: ghcr.io/williamstam/tradingbot:latest
    restart: unless-stopped
    links:
      - "db:db"
    depends_on:
      - db
    networks:
      - tradingbot
    environment:
      - API_BASE=${API_BASE}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}

      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}

networks:
  tradingbot:
